name: Check Completeness

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: all entries made
      run: bash ./.github/workflows/check-complete.sh

    - name: Run and collect coverage
      run: |
          coverage run --branch typewise_alert.test.py
          coverage html
          coverage report
    - name: Upload coverage
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: ./htmlcov
          retention-days: 21


